apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-wordpress
  name: wordpress
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mysql-wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-wordpress
        tier: frontend
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-secret-password
        image: wordpress
        imagePullPolicy: Always
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-storage
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-hostpath
